[package]
name = "problem1Rust"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "problem1Rust"
path = "src/problem1.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
